    - name: Installing go
      apt: 
        name: golang 
    
    - name: Clone calc-sum from github
      git: 
       repo: https://github.com/nbelousova/calc-sum.git
       dest: /srv/goapp
    - name: Delete .git
      file: path=/srv/goapp/.git state=absent
    - name: Create goapp service file
      template: src=goapp.service dest=/etc/systemd/system/goapp.service

    - name: Start goapp service
      command: systemctl start goapp
    - name: Create sum nginx location
      template: src=sum.location.conf.j2 dest=/etc/nginx/sites-available/{{ inventory_hostname }}.sum.location  owner=root group=root mode=0644
      notify: reload nginx
