    - name: Clone  front app from github
      git: 
       repo: https://github.com/nbelousova/calc-front.git
       dest: /srv
    - name: Delete .git
      file: path=/srv/.git state=absent
    - name: Create nginx location conf
      template: src=calc-front.location.nginx.j2 dest=/etc/nginx/sites-available/{{ inventory_hostname }}.calc-front.location  owner=root group=root mode=0644
      notify: reload nginx
