- name: Clone calc-diff from GitHub
  git: 
   repo: https://github.com/nbelousova/calc-diff.git
   dest: /srv/php
- name: Delete .git
  file: path=/srv/php/.git state=absent

- name: Add php nginx conf
  template: src=diff.location.conf.j2 dest=/etc/nginx/sites-available/{{ inventory_hostname }}.diff.location owner=root group=root mode=0644
  notify: reload nginx
      
